FROM node:16-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY . .

# Expose the dev server port
EXPOSE 3000

# Start app in development mode
CMD ["npm", "start"]